server.ssl.key-store=classpath:identity.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=changeit
server.ssl.key-password=changeit

server.ssl.trust-store=classpath:http-trust.jks
server.ssl.trust-store-password=changeit

server.port=8080

server.ssl.client-auth=need

# Disable autorun, We run Liquibase explicitly in a PostConstruct
spring.liquibase.enabled=false
spring.liquibase.url=jdbc:cassandra://localhost:9042/my_keyspace?localdatacenter=datacenter1&compliancemode=Liquibase&enableSsl=false
spring.liquibase.username=local
spring.liquibase.password=local